service: aws-js-api
app: freelanceapp
org: mycompanyname

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 300
  timeout: 120
  architecture: x86_64
  region: eu-north-1
  stackTags:
    product: sojin-team
    env: qa
    terraform: false
    created-date: 2024-01-03
    team: data
    customer-impact: false

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /hello
          method: post
